name: Build and push docker images for git tag

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: kennyopennix/wazuh-agent
          - dockerfile: ./images/Dockerfile.amazonlinux
            image: kennyopennix/wazuh-agent-amazonlinux
          - dockerfile: ./images/Dockerfile.ubuntu
            image: kennyopennix/wazuh-agent-ubuntu
          - dockerfile: ./Dockerfile
            image: opennix/wazuh-agent
          - dockerfile: ./images/Dockerfile.amazonlinux
            image: opennix/wazuh-agent-amazonlinux
          - dockerfile: ./images/Dockerfile.ubuntu
            image: opennix/wazuh-agent-ubuntu
    steps:

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Agent version
        shell: bash
        run: echo "AGENT_VERSION=$(echo ${GITHUB_REF##*/} | sed 's/v//g')" >> $GITHUB_ENV

      - name: Set Docker tag
        shell: bash
        run: echo "TAG_NAME=$(echo ${GITHUB_REF##*/} | sed 's/v//g'|sed 's/-1//g')" >> $GITHUB_ENV

      - name: Docker tag and agent version
        run: |
          echo "All envs ${{ env }}"
          echo "New docker image tag ${{ env.TAG_NAME }}"
          echo "Wazuh agent version ${{ env.AGENT_VERSION }}"

      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        continue-on-error: true
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.image }}:${{ env.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
              AGENT_VERSION=${{ env.AGENT_VERSION }}
